# Generated by Django 5.1.5 on 2026-01-29 03:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0008_alter_batch_user_alter_category_user_and_more'),
        ('production', '0003_billofmaterial_products_alter_billofmaterial_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceabilityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_threshold_kg', models.DecimalField(decimal_places=3, default=0.1, help_text='Si queda menos de esta cantidad, se descarta como merma (kg)', max_digits=5)),
                ('low_stock_threshold_kg', models.DecimalField(decimal_places=2, default=5.0, help_text='Alerta si el stock total está por debajo de este valor (kg)', max_digits=10)),
                ('expiry_alert_days', models.IntegerField(default=90, help_text='Días antes del vencimiento para generar alerta')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Trazabilidad',
                'verbose_name_plural': 'Configuraciones de Trazabilidad',
            },
        ),
        migrations.CreateModel(
            name='IngredientLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(help_text='ID interno generado automáticamente (ej: MP-MAL-001)', max_length=50, unique=True)),
                ('quantity_initial', models.DecimalField(decimal_places=3, help_text='Cantidad inicial al recibir (kg)', max_digits=10)),
                ('quantity_current', models.DecimalField(decimal_places=3, help_text='Cantidad actual disponible (kg)', max_digits=10)),
                ('supplier_lot', models.CharField(help_text='Lote del proveedor', max_length=100)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False si fue consumido totalmente o descartado')),
                ('is_wasted', models.BooleanField(default=False, help_text='True si fue descartado por merma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='inventory.ingredient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Ingrediente',
                'verbose_name_plural': 'Lotes de Ingredientes',
                'ordering': ['received_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_lot_code', models.CharField(help_text='Código de lote interno (ej: L-240130-01)', max_length=50, unique=True)),
                ('quantity_produced', models.DecimalField(decimal_places=3, help_text='Cantidad producida (kg)', max_digits=10)),
                ('production_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Proceso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, help_text='Receta utilizada', null=True, on_delete=django.db.models.deletion.PROTECT, to='production.billofmaterial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='inventory.product')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='production.productionorder')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lote de Producción',
                'verbose_name_plural': 'Lotes de Producción',
                'ordering': ['-production_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_consumed', models.DecimalField(decimal_places=3, help_text='Cantidad consumida de este lote (kg)', max_digits=10)),
                ('is_waste', models.BooleanField(default=False, help_text='True si fue descartado como merma (< umbral)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(help_text='Redundante pero útil para queries', on_delete=django.db.models.deletion.PROTECT, to='inventory.ingredient')),
                ('ingredient_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='traceability.ingredientlot')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='traceability.productionbatch')),
            ],
            options={
                'verbose_name': 'Consumo de Lote',
                'verbose_name_plural': 'Consumos de Lotes',
                'ordering': ['production_batch', 'ingredient'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Stock Bajo'), ('NEAR_EXPIRY', 'Próximo a Vencer'), ('EXPIRED', 'Vencido')], max_length=20)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.ingredient')),
                ('ingredient_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='traceability.ingredientlot')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
