# Generated by Django 5.1.5 on 2026-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='allocated_date',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se asignó completamente', null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='is_allocated',
            field=models.BooleanField(default=False, help_text='True si todo el lote fue asignado a ventas'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='quantity_remaining',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='kg disponibles para venta (no asignados)', max_digits=10, null=True),
        ),
    ]
