# Generated by Django 5.1.5 on 2026-01-29 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_stock_deducted'),
        ('traceability', '0002_productionbatch_allocated_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_allocated', models.DecimalField(decimal_places=3, help_text='kg asignados de este lote a esta venta', max_digits=10)),
                ('allocation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_batch', models.ForeignKey(help_text='Lote de producción usado para cumplir esta venta', on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='traceability.productionbatch')),
                ('sale_item', models.ForeignKey(help_text='Item de venta asignado', on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='sales.saleitem')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la asignación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación de Lote a Venta',
                'verbose_name_plural': 'Asignaciones de Lotes a Ventas',
                'ordering': ['allocation_date'],
                'indexes': [models.Index(fields=['sale_item', 'production_batch'], name='traceabilit_sale_it_701800_idx'), models.Index(fields=['production_batch'], name='traceabilit_product_c0ec22_idx')],
            },
        ),
    ]
