# Generated by Django 5.1.5 on 2026-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0003_salebatchallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchconsumption',
            name='quantity_consumed',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad consumida de este lote (kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientlot',
            name='quantity_current',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad actual disponible (kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredientlot',
            name='quantity_initial',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad inicial al recibir (kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad producida (kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='quantity_remaining',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='kg disponibles para venta (no asignados)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salebatchallocation',
            name='quantity_allocated',
            field=models.DecimalField(decimal_places=2, help_text='kg asignados de este lote a esta venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='traceabilityconfig',
            name='waste_threshold_kg',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Si queda menos de esta cantidad, se descarta como merma (kg)', max_digits=5),
        ),
    ]
