# Generated by Django 6.0 on 2025-12-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_assetcategory_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT/Tax ID'),
        ),
        migrations.AddField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this provider', null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
