# Generated by Django 6.0 on 2025-12-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_provider_contact_info_provider_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Administrativos'), ('ADVERTISING', 'Publicidad y Marketing'), ('FINANCIAL', 'Financieros'), ('PLATFORM', 'Plataforma y Tecnología'), ('INDIRECT', 'Costos Indirectos'), ('COMMERCIAL', 'Comisiones y Comercial'), ('TAXES', 'Impuestos y Tasas'), ('OTHER', 'Otros')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Administrativos'), ('ADVERTISING', 'Publicidad y Marketing'), ('FINANCIAL', 'Financieros'), ('PLATFORM', 'Plataforma y Tecnología'), ('INDIRECT', 'Costos Indirectos'), ('COMMERCIAL', 'Comisiones y Comercial'), ('TAXES', 'Impuestos y Tasas'), ('OTHER', 'Otros')], default='OTHER', max_length=20),
        ),
    ]
