# Generated by Django 6.0 on 2025-12-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fixedcost_category_monthlyexpense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Gastos Administrativos'), ('ADVERTISING', 'Publicidad y Marketing'), ('COMMERCIAL', 'Comisiones de Venta'), ('FINANCIAL', 'Costos Financieros y Bancarios'), ('FINANCING', 'Adelanto de Dinero / Intereses'), ('PLATFORM', 'Plataforma y Tecnología (Tienda Nube)'), ('LOGISTICS', 'Logística y Envíos'), ('INDIRECT', 'Costos Indirectos de Fabricación'), ('TAXES', 'Impuestos y Tasas'), ('OTHER', 'Otros Gastos')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='category',
            field=models.CharField(choices=[('ADMINISTRATIVE', 'Gastos Administrativos'), ('ADVERTISING', 'Publicidad y Marketing'), ('COMMERCIAL', 'Comisiones de Venta'), ('FINANCIAL', 'Costos Financieros y Bancarios'), ('FINANCING', 'Adelanto de Dinero / Intereses'), ('PLATFORM', 'Plataforma y Tecnología (Tienda Nube)'), ('LOGISTICS', 'Logística y Envíos'), ('INDIRECT', 'Costos Indirectos de Fabricación'), ('TAXES', 'Impuestos y Tasas'), ('OTHER', 'Otros Gastos')], default='OTHER', max_length=20),
        ),
    ]
