# Generated by Django 6.0 on 2025-12-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_fixedcost_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='ID de la operación origen', max_length=100, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(db_index=True, max_length=100)),
                ('payment_method_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxes_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('real_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('money_release_date', models.DateTimeField(blank=True, null=True)),
                ('business_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['source_id', 'transaction_type'], name='finance_mer_source__ab968b_idx')],
            },
        ),
    ]
