# Generated by Django 6.0 on 2025-12-20 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_mercadopagosettlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='external_reference',
            field=models.CharField(blank=True, help_text='Referencia externa (ej. ID de pedido en tienda)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión de Mercado Pago (negativo)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='money_release_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de liberación de fondos (Cashflow)', null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='payment_method_type',
            field=models.CharField(blank=True, help_text='Medio de pago: credit_card, debit_card, available_money', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='real_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto Neto liberado (Bruto + Fees + Impuestos)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='settlement_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de liquidación administrativa', null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID de la operación origen (SOURCE_ID)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='taxes_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Impuestos/Retenciones (negativo)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto Bruto de la operación', max_digits=14),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='transaction_date',
            field=models.DateTimeField(blank=True, help_text='Fecha en que ocurrió la transacción', null=True),
        ),
        migrations.AlterField(
            model_name='mercadopagosettlement',
            name='transaction_type',
            field=models.CharField(db_index=True, help_text='Tipo de transacción: SETTLEMENT, PAYOUTS, REFUND, etc.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='mercadopagosettlement',
            index=models.Index(fields=['money_release_date'], name='finance_mer_money_r_5c6ed3_idx'),
        ),
    ]
