# Generated by Django 6.0 on 2025-12-24 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_mercadopagosettlement_external_reference_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mercadopagosettlement',
            name='finance_mer_source__ab968b_idx',
        ),
        migrations.RemoveIndex(
            model_name='mercadopagosettlement',
            name='finance_mer_money_r_5c6ed3_idx',
        ),
        migrations.DeleteModel(
            name='MercadoPagoSettlement',
        ),
    ]
