# Generated by Django 6.0 on 2025-12-24 01:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0011_remove_mercadopagosettlement_finance_mer_source__ab968b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto absoluto', max_digits=14)),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=10)),
                ('category', models.CharField(choices=[('SALE', 'Venta'), ('EXPENSE', 'Gasto'), ('PURCHASE', 'Compra Insumos'), ('PAYROLL', 'Sueldos'), ('TAX', 'Impuestos'), ('LOAN', 'Préstamo/Financiamiento'), ('TRANSFER', 'Transferencia entre cuentas'), ('ADJUSTMENT', 'Ajuste'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('account', models.CharField(choices=[('CASH', 'Caja Chica / Efectivo'), ('BANK', 'Banco (Galicia/Santander/etc)'), ('MERCADOPAGO', 'Mercado Pago'), ('OTHER', 'Otros')], default='CASH', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
