# Generated by Django 6.0 on 2025-12-24 02:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_purchase_due_date_purchase_paid_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID externo para evitar duplicados (ej. MP)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CASH', 'Efectivo / Caja'), ('BANK', 'Banco'), ('WALLET', 'Billetera Virtual (MP, etc)'), ('OTHER', 'Otro')], default='CASH', max_length=20)),
                ('currency', models.CharField(default='ARS', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo al inicio', max_digits=14)),
                ('opening_date', models.DateField(default=django.utils.timezone.now, help_text='Fecha del saldo inicial')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='finance.account'),
        ),
    ]
