# Generated by Django 5.1.5 on 2026-01-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_batch_user_alter_category_user_and_more'),
        ('production', '0002_alter_billofmaterial_user_alter_productionorder_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='boms', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_boms', to='inventory.product'),
        ),
    ]
