# Generated by Django 5.1.5 on 2026-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_billofmaterial_products_alter_billofmaterial_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_PROGRESS', 'En Proceso'), ('DONE', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20),
        ),
    ]
