# Generated by Django 5.1.5 on 2026-02-19 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_category_options_alter_ingredient_options_and_more'),
        ('production', '0004_alter_productionorder_status'),
        ('traceability', '0003_salebatchallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Propel ERP', help_text='Nombre de la empresa para reportes', max_length=200)),
                ('technical_director_name', models.CharField(blank=True, default='', help_text='Nombre del Director Tecnico para CoA', max_length=200)),
                ('signature_image', models.ImageField(blank=True, help_text='Imagen de firma digitalizada del DT', null=True, upload_to='company/')),
                ('logo_image', models.ImageField(blank=True, help_text='Logo de la empresa para reportes PDF', null=True, upload_to='company/')),
            ],
            options={
                'verbose_name': 'Configuracion de Empresa',
                'verbose_name_plural': 'Configuracion de Empresa',
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(help_text='Nombre del parametro (ej: pH, Apariencia, Vitamina C)', max_length=200)),
                ('specification', models.CharField(help_text='Rango aceptable (ej: 4.5 - 5.5, Polvo blanco)', max_length=200)),
                ('method', models.CharField(blank=True, default='', help_text='Metodo de analisis (ej: HPLC, Visual, Potenciometrico)', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Orden de aparicion en el certificado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Especificacion de Producto',
                'verbose_name_plural': 'Especificaciones de Producto',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QualityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(help_text='Valor obtenido en el analisis', max_length=200)),
                ('approved', models.BooleanField(default=True)),
                ('tested_date', models.DateField(auto_now_add=True)),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_results', to='traceability.productionbatch')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='production.productspecification')),
            ],
            options={
                'verbose_name': 'Resultado de Calidad',
                'verbose_name_plural': 'Resultados de Calidad',
                'ordering': ['specification__sort_order'],
                'unique_together': {('production_batch', 'specification')},
            },
        ),
    ]
