# Generated by Django 5.1.5 on 2026-03-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_companyconfig_productspecification_qualityresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='company_address',
            field=models.CharField(blank=True, default='AV. BODEREAU 9116 LOCAL 2', help_text='Domicilio fiscal de la empresa', max_length=300),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_cuit',
            field=models.CharField(blank=True, default='30-71928199-7', help_text='CUIT de la empresa', max_length=20),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_email',
            field=models.CharField(blank=True, default='', help_text='Email de contacto / ventas', max_length=200),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_iva_condition',
            field=models.CharField(blank=True, default='RESPONSABLE INSCRIPTO', help_text='Condicion de IVA (Responsable Inscripto, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_phone',
            field=models.CharField(blank=True, default='', help_text='Telefono de contacto', max_length=50),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_social',
            field=models.CharField(blank=True, default='', help_text='Red social (ej: @formulavital.ar)', max_length=100),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='company_website',
            field=models.CharField(blank=True, default='', help_text='Sitio web de la empresa', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='company_name',
            field=models.CharField(default='INSAF', help_text='Nombre de la empresa para reportes', max_length=200),
        ),
    ]
