# Generated by Django 5.1.5 on 2026-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_add_company_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Cantidad requerida', max_digits=10),
        ),
    ]
