# Generated by Django 5.1.5 on 2026-03-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_product_weight_kg'),
        ('production', '0007_alter_bomline_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInProcessStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('MIXED', 'Mezclado (polvo suelto)'), ('PACKAGED', 'Envasado (sin etiquetar)')], help_text='Etapa de producción', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Cantidad disponible en esta etapa', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('u', 'Unidades')], default='kg', help_text='Unidad de medida', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notas (ej: tupper azul, pote sin cuchara)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Producto al que corresponde este WIP', on_delete=django.db.models.deletion.CASCADE, related_name='wip_stocks', to='inventory.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock en Proceso (WIP)',
                'verbose_name_plural': 'Stock en Proceso (WIP)',
                'ordering': ['stage', 'product__name'],
            },
        ),
    ]
