# Generated by Django 5.1.5 on 2026-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_workinprocessstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomline',
            name='scrap_factor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='% de desperdicio estimado', max_digits=5),
        ),
    ]
