# Generated by Django 6.0 on 2025-12-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_productionorder_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Peso neto por unidad (para cálculo de recetas)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros')], default='g', max_length=10),
        ),
    ]
