# Generated by Django 6.0 on 2025-12-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_net_weight_product_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('raw_material', 'Materia Prima (Fórmula)'), ('supply', 'Insumo (Packaging/Otros)')], default='raw_material', max_length=20),
        ),
    ]
