# Generated by Django 5.1.5 on 2026-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_batch_user_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Peso por unidad en kg (ej: 0.500 para botella de 500g)', max_digits=6),
        ),
    ]
