# Generated by Django 5.1.5 on 2026-01-29 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_weight_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'sku')},
        ),
    ]
