# Generated by Django 5.1.5 on 2026-02-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_product_sku_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='code',
            field=models.CharField(blank=True, help_text='Código único para identificación de lotes (ej: MGS, CIT, etc.)', max_length=10, null=True),
        ),
    ]
