# Generated by Django 5.1.5 on 2026-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_ingredient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(help_text='Código único para identificación de lotes (ej: MGS, CIT, etc.)', max_length=10, unique=True),
        ),
    ]
