# Generated by Django 5.1.5 on 2026-02-06 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_ingredient_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['code', 'name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sku', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['product', 'ingredient'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum stock threshold for alerts', max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed category description', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Category owner/creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(help_text='Unique code for lot identification (e.g., MGS, CIT, VITC)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Purchase cost per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Ingredient name', max_length=200),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current stock quantity', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('raw_material', 'Materia Prima (Fórmula)'), ('supply', 'Insumo (Packaging/Otros)')], default='raw_material', help_text='Ingredient type: raw material or supply', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros'), ('u', 'Unidades')], default='g', help_text='Measurement unit', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Ingredient owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Production/acquisition cost per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Net content weight per unit (for recipe calculations)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Selling price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit - unique product code', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity (units)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros')], default='g', help_text='Unit of measurement', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Product owner/creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Weight per unit in kg (e.g., 0.500 for 500g bottle)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(help_text='Required ingredient', on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(help_text='Product this recipe produces', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity required per product unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Recipe owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('product', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['code'], name='inventory_i_code_d3e5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['type'], name='inventory_i_type_9ab62a_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['stock_quantity'], name='inventory_i_stock_q_f3867b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='inventory_p_stock_q_e1fd3c_idx'),
        ),
    ]
