# Generated by Django 5.1.5 on 2026-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_ingredient_cost_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight per unit in kg (e.g., 0.500 for 500g bottle)', max_digits=6),
        ),
    ]
