# Generated by Django 5.1.5 on 2026-04-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_normalize_product_sku_lowercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.IntegerField(default=10, help_text='Minimum stock threshold for low-stock alerts. Customizable per product (was hardcoded to 10 before).'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('u', 'Unidades')], default='g', help_text='Unit of measurement', max_length=10),
        ),
    ]
