# Generated by Django 5.1.5 on 2026-04-28 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_add_product_min_stock_and_unit_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(help_text='Unique-per-user code for lot identification (e.g., MGS, CIT, VITC). Uniqueness is enforced via Meta.constraints, scoped to the owning user.', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='uniq_ingredient_user_code'),
        ),
    ]
