# Generated by Django 6.0 on 2025-12-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_product_net_weight_product_unit_measure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Comprador', max_length=255)),
                ('document_raw', models.CharField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_name', models.CharField(blank=True, help_text='Datos personales o de empresa', max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, help_text='Dirección', max_length=255, null=True)),
                ('tax_condition', models.CharField(blank=True, help_text='Condición fiscal', max_length=100, null=True)),
                ('shipping_address', models.CharField(blank=True, help_text='Domicilio', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='Ciudad', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='Estado/Provincia', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Código postal', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='País', max_length=100, null=True)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('is_wholesaler', models.BooleanField(default=False)),
                ('has_open_claim', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('first_order_date', models.DateTimeField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_order', models.IntegerField(default=0)),
                ('total_return_units', models.PositiveIntegerField(default=0)),
                ('return_rate', models.FloatField(default=0.0)),
                ('open_claims_count', models.PositiveIntegerField(default=0)),
                ('closed_claims_count', models.PositiveIntegerField(default=0)),
                ('mediated_claims_count', models.PositiveIntegerField(default=0)),
                ('r_score', models.PositiveSmallIntegerField(default=0)),
                ('f_score', models.PositiveSmallIntegerField(default=0)),
                ('m_score', models.PositiveSmallIntegerField(default=0)),
                ('segment', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='sales.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(help_text='# de venta', max_length=50, unique=True)),
                ('date', models.DateTimeField(help_text='Fecha de venta')),
                ('status', models.CharField(help_text='Estado del pedido', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total (ARS)', max_digits=12)),
                ('product_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos por productos', max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costos de envío', max_digits=12)),
                ('listing_fee', models.DecimalField(decimal_places=2, default=0, help_text='Cargo por venta + Costo fijo + Cuotas', max_digits=12)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, help_text='Impuestos', max_digits=12)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, help_text='Descuentos', max_digits=12)),
                ('shipping_income', models.DecimalField(decimal_places=2, default=0, help_text='Ingresos por envío', max_digits=12)),
                ('shipping_option', models.CharField(blank=True, help_text='Forma de entrega', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Número de seguimiento', max_length=100, null=True)),
                ('buyer_dni', models.CharField(blank=True, help_text='DNI del comprador', max_length=50, null=True)),
                ('buyer_address', models.TextField(blank=True, help_text='Domicilio', null=True)),
                ('province', models.CharField(blank=True, help_text='Estado/Provincia', max_length=100, null=True)),
                ('city', models.CharField(blank=True, help_text='Ciudad', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, help_text='Código postal', max_length=20, null=True)),
                ('invoice_data', models.TextField(blank=True, help_text='Datos para facturación', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.customer')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=300)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
