# Generated by Django 6.0 on 2025-12-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='has_open_claim',
            field=models.BooleanField(default=False, help_text='Tiene reclamo abierto'),
        ),
    ]
