# Generated by Django 6.0 on 2025-12-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_user_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('MERCADOLIBRE', 'Mercado Libre'), ('WHOLESALE', 'Mayorista'), ('TIENDANUBE', 'Tienda Nube')], default='MERCADOLIBRE', max_length=20),
        ),
    ]
