# Generated by Django 6.0 on 2025-12-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='buyer_notes',
            field=models.TextField(blank=True, help_text='Notas del comprador', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='currency',
            field=models.CharField(default='ARS', help_text='Moneda', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de pago', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Medio de pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(blank=True, help_text='Estado del pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Nombre para el envío', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Teléfono para el envío', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller_notes',
            field=models.TextField(blank=True, help_text='Notas del vendedor', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de envío', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_status',
            field=models.CharField(blank=True, help_text='Estado del envío', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID Transacción Pago', max_length=100, null=True),
        ),
    ]
