# Generated by Django 6.0 on 2026-01-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_due_date_sale_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstats',
            name='return_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tasa de devolución (%)', max_digits=5),
        ),
    ]
