# Generated by Django 6.0 on 2026-01-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_convert_return_rate_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Si el stock ya fue descontado'),
        ),
    ]
