# Generated by Django 5.1.5 on 2026-02-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_stock_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('MERCADOLIBRE', 'Mercado Libre'), ('WHOLESALE', 'Mayorista'), ('TIENDANUBE', 'Tienda Nube'), ('PARTICULAR', 'Particular')], default='MERCADOLIBRE', max_length=20),
        ),
    ]
