# Generated by Django 5.1.5 on 2026-02-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sale_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order_id',
            field=models.CharField(blank=True, help_text='ID de pedido (Mercado Libre, etc)', max_length=100, null=True),
        ),
    ]
