# Generated by Django 5.1.5 on 2026-02-24 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_category_options_alter_ingredient_options_and_more'),
        ('sales', '0011_make_order_id_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, help_text='Nro de presupuesto auto-generado', max_length=20, unique=True)),
                ('date', models.DateField(help_text='Fecha de emisión')),
                ('valid_until', models.DateField(help_text='Válido hasta')),
                ('sale_type', models.CharField(choices=[('WHOLESALE', 'Mayorista'), ('RETAIL', 'Minorista')], default='WHOLESALE', help_text='Tipo de venta', max_length=20)),
                ('sale_condition', models.CharField(choices=[('CONTADO', 'Contado'), ('CTA_CTE', 'Cuenta Corriente'), ('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia')], default='CTA_CTE', help_text='Condición de venta', max_length=20)),
                ('payment_terms', models.CharField(blank=True, help_text='Condiciones de pago (ej: 30 días)', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observaciones / condiciones especiales', null=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Bonificación global %', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción del producto', max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario', max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Bonificación por línea %', max_digits=5)),
                ('iva_pct', models.DecimalField(decimal_places=2, default=21, help_text='% IVA', max_digits=5)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
