# Generated by Django 5.1.5 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel_payment_status',
            field=models.CharField(blank=True, help_text='Estado del pago (canal de venta)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Stock descontado'),
        ),
    ]
