# Generated by Django 5.1.5 on 2026-04-29 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sale_channel_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='channel_payment_status',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='number',
            field=models.CharField(editable=False, help_text='Nro de presupuesto auto-generado', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='Si el stock ya fue descontado'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('user', 'number'), name='uniq_quotation_user_number'),
        ),
    ]
