# Generated by Django 5.1.5 on 2026-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_quotation_per_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='external_payment_status',
            field=models.CharField(blank=True, help_text='Estado de pago según el canal externo', max_length=100, null=True),
        ),
    ]
