# Generated by Django 5.1.5 on 2026-05-03 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_sale_external_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha de la devolución')),
                ('reason', models.TextField(blank=True, default='', help_text='Motivo de la devolución')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('APPROVED', 'Aprobada'), ('POSTED', 'Procesada')], default='DRAFT', max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Monto reintegrado al cliente (calculado al postear)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Ventas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('restocked', models.BooleanField(default=True, help_text='Si el producto vuelve al stock')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.saleitem')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salereturn')),
            ],
            options={
                'verbose_name': 'Item devuelto',
                'verbose_name_plural': 'Items devueltos',
            },
        ),
    ]
